package geometri;

import java.awt.Color;

public abstract class GeometricalShape implements GeometricalForm {
	
	/** The object's position */
	private int x;
	private int y;
	
	/** The object's color */
	private Color color;
	
	public GeometricalShape ( int x, int y, Color c) {
		this.x = x;
		this.y = y;
		this.color = c; // clone?
	}
	
	public GeometricalShape ( GeometricalForm f, Color c ) {
		  this.x = f.getX();
		  this.y = f.getY();
		  this.color = c;
	}
	
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int compareTo(GeometricalForm f) {
		// TODO Auto-generated method stub
		if ( this.area() == f.area() ) {
			if ( this.perimeter() < f.perimeter() )
				return -2;
			if ( this.perimeter() > f.perimeter() )
				return 2;
			return 0;
		}
		
		if ( this.area() > f.area() )
			return 1;
		
		return -1;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public Color getColor() {
		// TODO Auto-generated method stub
		return this.color;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int getX() {
		return this.x;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
    public int getY() {
    	return this.y;
    }
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public void move(int dx, int dy) throws IllegalPositionException {
		// TODO Auto-generated method stub
		this.x += dx;
		this.y += dy;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public void place(int x, int y) throws IllegalPositionException {
		// TODO Auto-generated method stub
		this.x = x;
		this.y = y;
	}

	// Eclipse autogenerated these fuck yeah!
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((color == null) ? 0 : color.hashCode());
		result = prime * result + x;
		result = prime * result + y;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GeometricalShape other = (GeometricalShape) obj;
		if (color == null) {
			if (other.color != null)
				return false;
		} else if (!color.equals(other.color))
			return false;
		if (x != other.x)
			return false;
		if (y != other.y)
			return false;
		return true;
	}
	
	
	
	/**
	 * Set the position of the object according to the parameters.
	 * @param x Horizontal position of the point.
	 * @param y Vertical position of the point.
	 */
	/*public void setPosition( int x, int y ) {
		
	}
	*/
	
	//TODO add equals
	
	//TODO add hashCode
	
}
